language: cpp

jobs:
  include:
   - name: "Ubuntu 18.04"
     os: linux
     dist: bionic
     compiler: gcc
     script: make
 
   - name: "Windows Visual Studio 2017"
     os: windows
     env:
       - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
       - PATH=$MSBUILD_PATH:$PATH
     script:
       - cmd //c "MSBuild.exe UxVSim.vcxproj /m /t:Rebuild /p:Configuration=Release"
