on: [push, pull_request]
jobs:
 j1:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - run: make

 j2:
    name: Windows Visual Studio 2019 x64
    runs-on: windows-2019
    steps: 
    - uses: actions/checkout@v3
    - run: set PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin;%PATH% & MSBuild.exe UxVSim.vcxproj /m /t:Rebuild /p:Configuration=Release
      shell: cmd
